### ISSUE TITLE
Inbound cannot detect incoming message

### ISSUE THREAD

**Issue by alfarioekaputra** [wso2-extensions/esb-inbound-iso8583#8]
Hi Kanapriya,

I've been tested using test client, but the inbound doesn't show anything, but when I close test client, the message "ERROR - ConnectionRequestHandler Client may be disconnect the connection" shown up

It seems inbound listening on port 5000, but the inbound cannot detect incoming message

Can you elaborate this case, I've follow tutorial from https://docs.wso2.com/display/ESBCONNECTORS/Configuring+ISO8583+Inbound+Operations

my inbound enpoint

`<?xml version="1.0" encoding="UTF-8"?>
<inboundEndpoint
  class="org.wso2.carbon.inbound.iso8583.listening.ISO8583MessageConsumer"
  name="iso8583_listener" onError="fault" sequence="request"
  suspend="false" xmlns="http://ws.apache.org/ns/synapse">
  <parameters>
    <parameter name="port">5000</parameter>
    <parameter name="sequential">true</parameter>
    <parameter name="inbound.behavior">listening</parameter>
  </parameters>
</inboundEndpoint>
`

i use this client [https://github.com/jPOS/jPOS-template](https://github.com/jPOS/jPOS-template) for test the inbound.

the isomsg outgoing

`<isomsg direction="outgoing">
      
      <field id="0" value="0200"/>
      <field id="3" value="500000"/>
      <field id="4" value="000000060000"/>
      <field id="11" value="002071"/>
      <field id="12" value="083230"/>
      <field id="13" value="0901"/>
      <field id="15" value="0901"/>
      <field id="18" value="6014"/>
      <field id="32" value="111"/>
      <field id="41" value="BANK"/>
      <field id="42" value="000000000101900"/>
      <field id="48" value="216205273                                                                                                                                                                                        "/>
    </isomsg>`

**Comment by Kanapriya** [comment]
In what format ISOMessages send from client to inbound ?.
The current implementation scenario is, client send iso8583 string messages and inbound consume the string message and parse it into xml format and set into the sequence.
With the inbound, I have used java-client to send ISOMessages(0200B2200000001000000000000000800000568923000000100500011056328045689305kamal021ABCDEFGHIJ 1234567890) to inbound, and I got the following log in console (In that format messages are inject into the sequence) .
`[2016-09-06 15:50:16,616]  INFO - LogMediator To: , MessageID: urn:uuid:46AE247541E2576CF81473157216575, Direction: request, Envelope: <?xml version='1.0' encoding='utf-8'?><soapenv:Envelope xmlns:soapenv="http://www.w3.org/2003/05/soap-envelope"><soapenv:Body><ISOMessage><data><field id="0">0200</field><field id="3">568923</field><field id="4">000000100500</field><field id="7">0110563280</field><field id="11">456893</field><field id="44">KAMAL</field><field id="105">ABCDEFGHIJ 1234567890</field></data></ISOMessage></soapenv:Body></soapenv:Envelope>
`

**Comment by alfarioekaputra** [comment]
hello kanapriya

I'm finally succeed send ISO8583 message from your testclient to my inbound, but forgive my foolishness, I'm very very newbi in this area, would you like give me examples of the use of sequence in this case, maybe a link for tutorial using real examples, thank you

**Comment by aman-rohiman** [comment]
Hello Kanapriya,
The first of all, you're doing great job with this extension.
But unfortunately, I'm facing same problem too, I can extract ISOMessage, send it into the sequence, but after that, I don't know how to alter data and send it back to client.
I search on wso2 documentation, how to respond message in inbound, but I can't find anything.
Maybe you can show us how to handle incoming ISOMessage, alter it, and send it back to client?
Do we need create connector or just simply modify data in sequence?
Thank you.

**Comment by rajeshfern** [comment]
Hello Kanapriya,

How to handle ISO 8583:1993 format message,Jpos jar does not unpack 1993 message based on iso1993 xml,it's unpack using iso1987 xml
ISO Message(18040030010000000000468560200225110824801)

**Comment by rajeshfern** [comment]
Hi guys,
i am facing a issue while unpack the ISO 8583:1993 message,finally i found a simple solution.just right click on org.wso2.carbon.inbound.iso8583-1.0.0.jar open with winrar archiver open jposdef.xml replace the following reference xml then save <a>https://github.com/jpos/jPOS/blob/master/jpos/src/main/resources/packager/iso93ascii.xml</a>
now it will unpack the ISO 8583:1993 messge

**Comment by anupama-pathirage** [comment]
Moved to https://github.com/wso2/micro-integrator/issues/3520
